### ISSUE TITLE
npm init

### ISSUE THREAD

**Issue by edsondearaujo** [edsondearaujo/HTTP_with_Node#1]
# Description
Create project

# Tasks
- [x] Run comand npm init
- [x] Setup package.json (Start: node index)
- [x] Setup server on the index.js
